### PR TITLE
feat(CustomUrl): Adds ability to set custom favicons by url

### LINKED ISSUE #4: Update, Is it possible to use dynamical external fav ?
Hi, I just wanted to know if it's possible to dynamically load a favicon and use it ?

### PR DESCRIPTION
**Pull request by zakhenry**
Closes #4

### CODE REVIEW

**Review by maxime1992 — APPROVED** [review]
Nice one @zakhenry ! :smiley:

**Comment by evanlegamer** [comment]
Maybe, it could be great if you put your changes in the readme, to explain how we can define a favicon by url. I know we can see the example in the example app, but some people prefer to see it fastly in the readme :) @maxime1992

**Comment by maxime1992** [comment]
Woups completely forgot about that thanks for reporting it :)

**Comment by maxime1992** [comment]
@evanlegamer it's done, readme updated :)

**Comment by evanlegamer** [comment]
Cool thank you :)

**Pull request merged**
